# Farewell is an addon PaperMC plugin for BromineMC designed to sunset the server.
#
# Copyright (C) 2025 BromineMC
# Copyright (C) 2025 VidTu
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[versions]
error_prone_annotations = "2.43.0"
jetbrains-annotations = "26.0.2"
jspecify = "1.0.0"
paper = "1.20.2-R0.1-SNAPSHOT" # Server version.
run-paper = "3.0.2"

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }

[libraries]
error_prone_annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "error_prone_annotations" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
